#!/usr/bin/env bash

set -eu

args=$*

case "${args}" in
    "rev-parse --abbrev-ref HEAD")
        echo $GITSHORTY_TEST_CURRENT_BRANCH
        ;;
    "--no-pager branch --format=%(refname:short)")
        IFS=':' read -ra LOCAL_BRANCHES <<< "$GITSHORTY_TEST_LOCAL_BRANCHES"
        for branch in "${LOCAL_BRANCHES[@]}"
        do
            echo "$branch"
        done
        ;;
    "--no-pager branch --remote --format=%(refname:short)")
        IFS=':' read -ra REMOTE_BRANCHES <<< "$GITSHORTY_TEST_REMOTE_BRANCHES"
        for branch in "${REMOTE_BRANCHES[@]}"
        do
            echo "$branch"
        done
        ;;
    "branch -D "*)
        branchName=${args:10}
        if [[ ! ":${GITSHORTY_TEST_LOCAL_BRANCHES}:" =~ ":${branchName}:" ]]; then
            echo "error: branch '$branchName' not found."
            exit 1
        fi
        ;;
    "push --delete "*)
        remoteSpaceBranch=${args:14}
        remoteSlashBranch=${remoteSpaceBranch/ /\/}
        if [[ ! ":${GITSHORTY_TEST_REMOTE_BRANCHES}:" =~ ":${remoteSlashBranch}:" ]]; then
            echo "error: unable to delete '$remoteSlashBranch': remote ref does not exist"
            exit 1
        fi
        ;;
    *)
        echo "Unknown command: '${args}'"
        exit 1
        ;;
esac
