/*
 * Shortcut API
 *
 * Shortcut API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sc

// A group of Member profile details.
type Profile struct {
	// A string description of this resource.
	EntityType string `json:"entity_type"`
	// A true/false boolean indicating whether the Member has been deactivated within Shortcut.
	Deactivated bool `json:"deactivated"`
	// If Two Factor Authentication is activated for this User.
	TwoFactorAuthActivated bool `json:"two_factor_auth_activated,omitempty"`
	// The Member's username within the Organization.
	MentionName string `json:"mention_name"`
	// The Member's name within the Organization.
	Name string `json:"name"`
	// This is the gravatar hash associated with email_address.
	GravatarHash string `json:"gravatar_hash"`
	// The unique identifier of the profile.
	Id string `json:"id"`
	DisplayIcon *Icon `json:"display_icon"`
	// A boolean indicating whether this profile is an owner at their associated organization.
	IsOwner bool `json:"is_owner"`
	// The primary email address of the Member with the Organization.
	EmailAddress string `json:"email_address"`
}
