/*
 * Shortcut API
 *
 * Shortcut API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sc

type CreateStories struct {
	// An array of stories to be created.
	Stories []CreateStoryParams `json:"stories"`
}
