/*
 * Shortcut API
 *
 * Shortcut API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sc

type UpdateLabel struct {
	// The new name of the label.
	Name string `json:"name,omitempty"`
	// The new description of the label.
	Description string `json:"description,omitempty"`
	// The hex color to be displayed with the Label (for example, \"#ff0000\").
	Color string `json:"color,omitempty"`
	// A true/false boolean indicating if the Label has been archived.
	Archived bool `json:"archived,omitempty"`
}
