/*
 * Shortcut API
 *
 * Shortcut API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sc

// True if the Story has archived, otherwise false.
type StoryHistoryChangeOldNewBool struct {
	// The old value.
	Old bool `json:"old,omitempty"`
	// The new value.
	New bool `json:"new,omitempty"`
}
