/*
 * Shortcut API
 *
 * Shortcut API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sc
import (
	"time"
)

// Workflow is the array of defined Workflow States. Workflow can be queried using the API but must be updated in the Shortcut UI. 
type Workflow struct {
	// A description of the workflow.
	Description string `json:"description"`
	// A string description of this resource.
	EntityType string `json:"entity_type"`
	// An array of IDs of projects within the Workflow.
	ProjectIds []float64 `json:"project_ids"`
	// A map of the states in this Workflow.
	States []WorkflowState `json:"states"`
	// The name of the workflow.
	Name string `json:"name"`
	// The date the Workflow was updated.
	UpdatedAt time.Time `json:"updated_at"`
	// Indicates if an owner is automatically assigned when an unowned story is started.
	AutoAssignOwner bool `json:"auto_assign_owner"`
	// The unique ID of the Workflow.
	Id int64 `json:"id"`
	// The ID of the team the workflow belongs to.
	TeamId int64 `json:"team_id"`
	// The date the Workflow was created.
	CreatedAt time.Time `json:"created_at"`
	// The unique ID of the default state that new Stories are entered into.
	DefaultStateId int64 `json:"default_state_id"`
}
