/*
 * Shortcut API
 *
 * Shortcut API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sc
import (
	"time"
)

// An Iteration is a defined, time-boxed period of development for a collection of Stories. See https://help.shortcut.com/hc/en-us/articles/360028953452-Iterations-Overview for more information.
type Iteration struct {
	// The Shortcut application url for the Iteration.
	AppUrl string `json:"app_url"`
	// The description of the iteration.
	Description string `json:"description"`
	// A string description of this resource
	EntityType string `json:"entity_type"`
	// An array of labels attached to the iteration.
	Labels []Label `json:"labels"`
	// `Deprecated:` use `member_mention_ids`.
	MentionIds []string `json:"mention_ids"`
	// An array of Member IDs that have been mentioned in the Story description.
	MemberMentionIds []string `json:"member_mention_ids"`
	// An array containing Group IDs and Group-owned story counts for the Iteration's associated groups.
	AssociatedGroups []IterationAssociatedGroup `json:"associated_groups"`
	// The name of the iteration.
	Name string `json:"name"`
	GlobalId string `json:"global_id"`
	// An array of label ids attached to the iteration.
	LabelIds []int64 `json:"label_ids"`
	// The instant when this iteration was last updated.
	UpdatedAt time.Time `json:"updated_at"`
	// An array of Group IDs that have been mentioned in the Story description.
	GroupMentionIds []string `json:"group_mention_ids"`
	// The date this iteration ends.
	EndDate time.Time `json:"end_date"`
	// An array of UUIDs for any Members listed as Followers.
	FollowerIds []string `json:"follower_ids"`
	// An array of UUIDs for any Groups you want to add as Followers. Currently, only one Group association is presented in our web UI.
	GroupIds []string `json:"group_ids"`
	// The date this iteration begins.
	StartDate time.Time `json:"start_date"`
	// The status of the iteration. Values are either \"unstarted\", \"started\", or \"done\".
	Status string `json:"status"`
	// The ID of the iteration.
	Id int64 `json:"id"`
	Stats *IterationStats `json:"stats"`
	// The instant when this iteration was created.
	CreatedAt time.Time `json:"created_at"`
}
