/*
 * Shortcut API
 *
 * Shortcut API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sc
import (
	"time"
)

type CreateMilestone struct {
	// The name of the Milestone.
	Name string `json:"name"`
	// The Milestone's description.
	Description string `json:"description,omitempty"`
	// The workflow state that the Milestone is in.
	State string `json:"state,omitempty"`
	// A manual override for the time/date the Milestone was started.
	StartedAtOverride time.Time `json:"started_at_override,omitempty"`
	// A manual override for the time/date the Milestone was completed.
	CompletedAtOverride time.Time `json:"completed_at_override,omitempty"`
	// An array of IDs of Categories attached to the Milestone.
	Categories []CreateCategoryParams `json:"categories,omitempty"`
}
