/*
 * Shortcut API
 *
 * Shortcut API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sc

type UpdateCustomFieldEnumValue struct {
	// The unique ID of an existing EnumValue within the CustomField's domain.
	Id string `json:"id,omitempty"`
	// A string value within the domain of this Custom Field.
	Value string `json:"value,omitempty"`
	// A color key associated with this EnumValue within the CustomField's domain.
	ColorKey string `json:"color_key,omitempty"`
	// Whether this EnumValue is enabled for its CustomField or not. Leaving this key out of the request leaves the current enabled state untouched.
	Enabled bool `json:"enabled,omitempty"`
}
