/*
 * Shortcut API
 *
 * Shortcut API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sc
import (
	"time"
)

// An entity template can be used to prefill various fields when creating new stories.
type EntityTemplate struct {
	// A string description of this resource.
	EntityType string `json:"entity_type"`
	// The unique identifier for the entity template.
	Id string `json:"id"`
	// The time/date when the entity template was created.
	CreatedAt time.Time `json:"created_at"`
	// The time/date when the entity template was last updated.
	UpdatedAt time.Time `json:"updated_at"`
	// The template's name.
	Name string `json:"name"`
	// The unique ID of the member who created the template.
	AuthorId string `json:"author_id"`
	// The last time that someone created an entity using this template.
	LastUsedAt time.Time `json:"last_used_at"`
	StoryContents *StoryContents `json:"story_contents"`
}
