/*
 * Shortcut API
 *
 * Shortcut API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sc

// Emoji reaction on a comment.
type StoryReaction struct {
	// Emoji text of the reaction.
	Emoji string `json:"emoji"`
	// Permissions who have reacted with this.
	PermissionIds []string `json:"permission_ids"`
}
