/*
 * Shortcut API
 *
 * Shortcut API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sc

// The changes that have occurred as a result of the action.
type HistoryChangesStoryLink struct {
	Verb *StoryHistoryChangeOldNewStr `json:"verb,omitempty"`
	ObjectId *StoryHistoryChangeOldNewInt `json:"object_id,omitempty"`
	SubjectId *StoryHistoryChangeOldNewInt `json:"subject_id,omitempty"`
}
