/*
 * Shortcut API
 *
 * Shortcut API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sc

// A reference to a Story.
type HistoryReferenceStory struct {
	// The ID of the entity referenced.
	Id *interface{} `json:"id"`
	// The type of entity referenced.
	EntityType string `json:"entity_type"`
	// The application URL of the Story.
	AppUrl string `json:"app_url"`
	// The name of the entity referenced.
	Name string `json:"name"`
	// If the referenced entity is a Story, either \"bug\", \"chore\", or \"feature\".
	StoryType string `json:"story_type"`
}
