/*
 * Shortcut API
 *
 * Shortcut API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sc

// A default reference for entity types that don't have extra fields.
type HistoryReferenceGeneral struct {
	// The ID of the entity referenced.
	Id *interface{} `json:"id"`
	// The type of entity referenced.
	EntityType string `json:"entity_type"`
	// The name of the entity referenced.
	Name string `json:"name"`
}
