/*
 * Shortcut API
 *
 * Shortcut API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sc

// A group of calculated values for this Project.
type ProjectStats struct {
	// The total number of stories in this Project.
	NumStories int64 `json:"num_stories"`
	// The total number of points in this Project.
	NumPoints int64 `json:"num_points"`
	// The total number of documents related to this Project
	NumRelatedDocuments int64 `json:"num_related_documents"`
}
