/*
 * Shortcut API
 *
 * Shortcut API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sc

// An action representing a bulk operation within a workspace2.
type HistoryActionWorkspace2BulkUpdate struct {
	// The ID of the entity referenced.
	Id string `json:"id"`
	// The type of entity referenced.
	EntityType string `json:"entity_type"`
	// The action of the entity referenced.
	Action string `json:"action"`
	// The name of the workspace2 in which the BulkUpdate occurred.
	Name string `json:"name"`
}
