/*
 * Shortcut API
 *
 * Shortcut API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sc

// An action representing a VCS Branch being created.
type HistoryActionBranchCreate struct {
	// The ID of the entity referenced.
	Id int64 `json:"id"`
	// The type of entity referenced.
	EntityType string `json:"entity_type"`
	// The name of the VCS Branch that was pushed
	Name string `json:"name"`
	// The URL from the provider of the VCS Branch that was pushed
	Url string `json:"url"`
	// The action of the entity referenced.
	Action string `json:"action"`
}
