/*
 * Shortcut API
 *
 * Shortcut API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sc

type UpdateGroup struct {
	// The description of this Group.
	Description string `json:"description,omitempty"`
	// Whether or not this Group is archived.
	Archived bool `json:"archived,omitempty"`
	// The color you wish to use for the Group in the system.
	Color string `json:"color,omitempty"`
	// The Icon id for the avatar of this Group.
	DisplayIconId string `json:"display_icon_id,omitempty"`
	// The mention name of this Group.
	MentionName string `json:"mention_name,omitempty"`
	// The name of this Group.
	Name string `json:"name,omitempty"`
	// The color key you wish to use for the Group in the system.
	ColorKey string `json:"color_key,omitempty"`
	// The Member ids to add to this Group.
	MemberIds []string `json:"member_ids,omitempty"`
	// The Workflow ids to add to the Group.
	WorkflowIds []int64 `json:"workflow_ids,omitempty"`
}
