/*
 * Shortcut API
 *
 * Shortcut API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sc
import (
	"time"
)

// Epic State is any of the at least 3 columns. Epic States correspond to one of 3 types: Unstarted, Started, or Done.
type EpicState struct {
	// The description of what sort of Epics belong in that Epic State.
	Description string `json:"description"`
	// A string description of this resource.
	EntityType string `json:"entity_type"`
	// The hex color for this Epic State.
	Color string `json:"color,omitempty"`
	// The Epic State's name.
	Name string `json:"name"`
	GlobalId string `json:"global_id"`
	// The type of Epic State (Unstarted, Started, or Done)
	Type_ string `json:"type"`
	// When the Epic State was last updated.
	UpdatedAt time.Time `json:"updated_at"`
	// The unique ID of the Epic State.
	Id int64 `json:"id"`
	// The position that the Epic State is in, starting with 0 at the left.
	Position int64 `json:"position"`
	// The time/date the Epic State was created.
	CreatedAt time.Time `json:"created_at"`
}
