/*
 * Shortcut API
 *
 * Shortcut API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sc

// Request parameters for creating a Story Link within a Story.
type CreateStoryLinkParams struct {
	// The unique ID of the Story defined as subject.
	SubjectId int64 `json:"subject_id,omitempty"`
	// How the subject Story acts on the object Story. This can be \"blocks\", \"duplicates\", or \"relates to\".
	Verb string `json:"verb"`
	// The unique ID of the Story defined as object.
	ObjectId int64 `json:"object_id,omitempty"`
}
