/*
 * Shortcut API
 *
 * Shortcut API
 *
 * API version: 3.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package sc

type BasicWorkspaceInfo struct {
	UrlSlug string `json:"url_slug"`
	EstimateScale []int64 `json:"estimate_scale"`
}
