name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.1

    - name: Build
      run: go build -v ./...

    - name: Mod tidy
      run: go mod tidy && git diff --exit-code go.mod go.sum

    - name: Test
      run: go test -v ./...
